version: '3.3'

services:
   db:
     image: postgres:11.4
     env_file: ".env"
     volumes:
       - ./db_data/:/docker-entrypoint-initdb.d/
     ports:
       - "5432:5432"
     restart: always

   nodejs:
     image: node:12.5.0
     env_file: ".env"
     depends_on:
       - db
     ports:
       - "8000:80"
       - "4433:443"
     working_dir: /usr/src/service/kilometry
     command: bash -c "npm install && npm run start"
     volumes:
       - .:/usr/src/service/kilometry
     restart: always

