version: '3'
services:
  api:
    container_name: "jobsova-api"
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    container_name: "jobsova-db"
    image: mysql:5.7
    env_file: 
    - ./db/.env
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always


